SKIP_TO_NTH = 3
SUBDIV_SIZE = 20
SUBDIV_RAD = 1

# Placement defs
MAX_VAL = 250
MIN_DIST =  5
SCALE_FACT = 25.0

# Enableable stuff
DO_IMAGE_LINEARIZATION = False
DARKEN_NOT_WHITE = True
DARKEN_EDGES = True
SMOOTH_KERNEL_RAD = 1
EDGE_KERNEL_RAD = 12
EDGE_DARKENING_RATIO = 1.0

STD_TRUNC_VAL = 13
STD_IGNORE_BLUE = True

MAX_DIMS = [1000, 1000]
MM_PER_PIX = 0.8


# Line placement defs
MAX_LINE_LEN = 30
CIRCLE_RAD = 5  

CIRCLE_RAD *= MM_PER_PIX

# MAX_DIMS = [500, 400]
# MAX_DIMS = [100, 150]