SKIP_TO_NTH = 3
SUBDIV_SIZE = 20
SUBDIV_RAD = 1

# Placement defs
MAX_VAL = 250
MIN_DIST =  5
SCALE_FACT = 25.0

# Enableable stuff
DO_IMAGE_LINEARIZATION = False
DARKEN_NOT_WHITE = True
DARKEN_EDGES = True
SMOOTH_KERNEL_RAD = 1
EDGE_KERNEL_RAD = 10
EDGE_DARKENING_RATIO = 0.4

# Line placement defs
MAX_LINE_LEN = 30

MAX_DIMS = [1000, 1500]
# MAX_DIMS = [500, 400]
# MAX_DIMS = [100, 150]